"""Corrected column

Revision ID: 20f3b94321d1
Revises: a2ff402cf8fe
Create Date: 2023-06-07 15:36:21.887671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20f3b94321d1'
down_revision = 'a2ff402cf8fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blobs', schema=None) as batch_op:
        batch_op.alter_column('compressed_data',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blobs', schema=None) as batch_op:
        batch_op.alter_column('compressed_data',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
