"""added method

Revision ID: 2bfe4484d868
Revises: 86732bdef26e
Create Date: 2023-06-08 18:15:09.060618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2bfe4484d868'
down_revision = '86732bdef26e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blobs', schema=None) as batch_op:
        batch_op.alter_column('compressed_data',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)

    with op.batch_alter_table('qrcodes', schema=None) as batch_op:
        batch_op.alter_column('qr_code_data',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qrcodes', schema=None) as batch_op:
        batch_op.alter_column('qr_code_data',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)

    with op.batch_alter_table('blobs', schema=None) as batch_op:
        batch_op.alter_column('compressed_data',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
