"""updated column

Revision ID: 35cdec7bcdd9
Revises: d79f5f3a5c2d
Create Date: 2023-06-06 10:26:52.007226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35cdec7bcdd9'
down_revision = 'd79f5f3a5c2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('compressed_data',
               existing_type=mysql.JSON(),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('compressed_data',
               existing_type=sa.BLOB(),
               type_=mysql.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###
