"""Creates a relationship between images and blobs tables

Revision ID: 3b1a22ceee12
Revises: 35cdec7bcdd9
Create Date: 2023-06-06 19:08:15.448899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b1a22ceee12'
down_revision = '35cdec7bcdd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('compressed_data', sa.LargeBinary(length=4294967295), nullable=True))
        batch_op.create_foreign_key(None, 'images', ['image_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('image_blob')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('compressed_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compressed_data', mysql.LONGBLOB(), nullable=True))

    with op.batch_alter_table('blobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_blob', sa.BLOB(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('compressed_data')
        batch_op.drop_column('image_id')

    # ### end Alembic commands ###
