"""remove and added column

Revision ID: 61861716c1f1
Revises: 20f3b94321d1
Create Date: 2023-06-07 21:04:53.493957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61861716c1f1'
down_revision = '20f3b94321d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blobs', schema=None) as batch_op:
        batch_op.alter_column('compressed_data',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
        batch_op.drop_column('filepath')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    with op.batch_alter_table('blobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', mysql.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('compressed_data',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
