"""added some method to the images table

Revision ID: 86732bdef26e
Revises: 61861716c1f1
Create Date: 2023-06-08 16:28:57.796585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86732bdef26e'
down_revision = '61861716c1f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qrcode', schema=None) as batch_op:
        batch_op.drop_index('id')

    op.drop_table('qrcode')
    with op.batch_alter_table('blobs', schema=None) as batch_op:
        batch_op.alter_column('compressed_data',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)

    with op.batch_alter_table('qrcodes', schema=None) as batch_op:
        batch_op.alter_column('qr_code_data',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qrcodes', schema=None) as batch_op:
        batch_op.alter_column('qr_code_data',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)

    with op.batch_alter_table('blobs', schema=None) as batch_op:
        batch_op.alter_column('compressed_data',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)

    op.create_table('qrcode',
    sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('qr_code_image_url', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('description', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('qrcode', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=False)

    # ### end Alembic commands ###
