"""Added a new column

Revision ID: a2ff402cf8fe
Revises: 3b1a22ceee12
Create Date: 2023-06-07 12:49:17.142351

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a2ff402cf8fe'
down_revision = '3b1a22ceee12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.String(length=255), nullable=True))
        batch_op.alter_column('compressed_data',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('file_name',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('file_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('blobs', schema=None) as batch_op:
        batch_op.alter_column('compressed_data',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
        batch_op.drop_column('file_name')

    # ### end Alembic commands ###
